name = "diskprices-worker"
main = "src/worker/index.ts"
compatibility_date = "2024-03-29"

[triggers]
crons = ["0 */6 * * *"] # 每6小时运行一次

[[kv_namespaces]]
binding = "DISK_PRICES"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[vars]
ENVIRONMENT = "production"

# 开发环境配置
[env.development]
name = "diskprices-worker-dev"
vars = { ENVIRONMENT = "development" }

# 生产环境配置
[env.production]
vars = { ENVIRONMENT = "production" }

[site]
bucket = "./dist"
entry-point = "src/worker" 